tags:
  5:
    x: 1.141
    y: -0.812
    z: 0.059525
    roll: 0
    pitch: 1.57
    yaw: 3.14

  6:
    x: 0.003
    y: -1.117
    z: 0.059525
    roll: 0
    pitch: 1.57
    yaw: 0.0

  7:
    x: 0.572
    y: -2.36
    z: 0.059525
    roll: 0
    pitch: 1.57
    yaw: 1.57

  0:
    x: 0.572
    y: -0.009
    z: 0.059525
    roll: 0
    pitch: 1.57
    yaw: -1.57